language: node_js
sudo: false
node_js:
- 4
- 6
- stable
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_d4f181ef7c79_key
  -iv $encrypted_d4f181ef7c79_iv -in auth.js.enc -out test/resources/auth.js -d ||
  true'
- npm install -g typescript
script:
- tsc # use the tsconfig.json to transpile specified service-files
- npm test
- npm run doc
after_success:
- scripts/jsdoc/publish.sh
